name: wasteagram
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  image_picker: 0.6.3
  intl: ^0.16.1
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  cloud_firestore: ^0.12.11
  firebase_storage: ^3.0.10
  firebase_core: 0.4.4
  firebase_auth: 0.15.0
  transparent_image: 1.0.0

dependency_overrides:

flutter:
  uses-material-design: true

